// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR3t_zzJAj0YUeyjsYUD8Z7BayA0D1RTY',
    appId: '1:321904179449:web:7d8fb84415928af69d0a28',
    messagingSenderId: '321904179449',
    projectId: 'covid-app-544dc',
    authDomain: 'covid-app-544dc.firebaseapp.com',
    storageBucket: 'covid-app-544dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB16aM2o8Ld-zJqLdZRvGYPUAkB1o6xWB8',
    appId: '1:321904179449:android:5025c7880dce1dde9d0a28',
    messagingSenderId: '321904179449',
    projectId: 'covid-app-544dc',
    storageBucket: 'covid-app-544dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi_flS_uEwAlLtH8_Xh9whbO4-ZLoxpCI',
    appId: '1:321904179449:ios:e0694f95d90b846c9d0a28',
    messagingSenderId: '321904179449',
    projectId: 'covid-app-544dc',
    storageBucket: 'covid-app-544dc.appspot.com',
    iosClientId: '321904179449-mp6h7002atjksc8nun2vn1jsj3revemn.apps.googleusercontent.com',
    iosBundleId: 'com.example.covid-app',
  );
}
